### ISSUE TITLE
Support Samples in Subdirectories

### ISSUE THREAD

**Issue by Finwood** [IRNAS/irnas-east-software#111]
## Context

The Zephyr repository itself has a huge number of samples, which are organized into multiple subfolders (e.g. [samples/drivers/](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/drivers)). It would be helpful when a structure like this would be supported by east's release process.

## Required steps / Implementation details

- define a scheme for `east.yaml` to allow specifying samples in subdirectories:
  - allow for a path to be specified as name (e.g. `name: drivers/dac`)
  - add an optional `path:` key, which overrides the path generated from the name
  - some other solution
- Implement using this path in the `east release` command

## Definition of Done

Samples in subdirectories can be added to `east.yaml`, documented in [configuation.md](https://github.com/IRNAS/irnas-east-software/blob/main/docs/configuration.md). These samples are picked up, compiled and released with `east release`. The compiled outputs are placed in the release folder following the same folder structure as the source code.

**Comment by MarkoSagadin** [comment]
Hello @Finwood. I have implemented this in https://github.com/IRNAS/irnas-east-software/commit/4d92bd4f1b4f25f890cec8bad8878eb52062c271. 

I have just triggered a new release, so soon you should be able to run `pip install --upgrade east-tool` and test the feature. Check the release notes for the use :)

**Comment by MarkoSagadin** [comment]
Also, please close this issue if you find the feature to be properly implemented.
