### ISSUE TITLE
Add update message to other commands

### ISSUE THREAD

**Issue by klancarLuka** [IRNAS/irnas-east-software#119]
## Context

As far as I've seen the only time the update text gets printed is when calling `east clean`

```
╭──────────────────────────────────────────────────────────────────────────────╮
│                                                                              │
│ New version of east is available!                                            │
│ Run pip install --upgrade east-tool to update.                               │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

```

It would greatly benefit the user experience if this message was printed with the use of other commands as well. It would be especially useful if the print would trigger when calling `east --version` or `east --help`, or other similar commands.

## Required steps / Implementation details

Depending on the implementation details adding the version check before each command could cause the opposite effect on the user experience (spamming the user, minor work delays), so only add the print where you deem it right. 
- [ ] Add new version print to `east --version` and/or `east --help`

## Definition of Done

- [ ] East tool prints "New version available" text with use of specified commands
- [ ] Code is reviewed and tested

**Comment by MarkoSagadin** [comment]
@klancarLuka this is not an issue anymore I assume?

**Comment by klancarLuka** [comment]
Not an issue ss discussed IRL :)
