### ISSUE TITLE
Suggestion - Change naming of generated files for samples in release process that don't inherit build types

### ISSUE THREAD

**Issue by TjazVracko** [IRNAS/irnas-east-software#52]
Any sample that does not inherit build types is build with the type `None` when the release command is used (see attached image). The `.hex/.elf/.bin` file generated thus has `-None` at the end of its name (e.g. `mysample-v0.1.3-None.hex`).

This is weird. I suggest you remove the `-None` part (e.g. `mysample-v0.1.3.hex`).

Also, it would probably be best to mark these samples with `/` instead of the word `None` in the table at the start of the release process:

![image](https://user-images.githubusercontent.com/26332685/221816950-2a1e5815-a0e6-484c-90e4-cbbd3ebc8eeb.png)

**Comment by MarkoSagadin** [comment]
I agree with both suggested changes.
