### ISSUE TITLE
BUG - compile_commands.json should be moved one folder higher

### ISSUE THREAD

**Issue by TjazVracko** [IRNAS/irnas-east-software#53]
Sometimes you want to open some file inside of zephyr or inside of ncs.
ctrl+click and stuff will not work in the current case.

If `compile_commands.json` would be copied to the folder one level above `project`, this would work.

**Comment by MarkoSagadin** [comment]
@TjazVracko This is easy to do, but are you sure that VSCode just does not know where to look for `compile_commands.json`?

Could this be resoled with proper configuration of    
`--compile-commands-dir` option in `settings.json`?

**Comment by TjazVracko** [comment]
Well, you have this: https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference (search for `compileCommands`).

But that is not sufficient, since we have multiple samples and apps, and you want the compile_commands.json to always be replaced with what you had last built.

**Comment by MarkoSagadin** [comment]
This was resolved in person and in above commit (de53337).

Use case is that if somebody uses terminal to move in the code directories and directly uses `code .` to open workspaces then clangd should still work.
