### ISSUE TITLE
Mac OS support

### ISSUE THREAD

**Issue by vid553** [IRNAS/irnas-east-software#98]
## Context

Since some developers use Mac OS to write NCS applications, it would be nice to have a proper support for this OS in East.
I'm opening this issue to track all the issues I run into, when trying to set it up.

System info:
- MacBook Pro M2, running MacOS Sonoma 14.0
- python 3.11.5
- west 1.1.0
- east 0.15.1

## Issues
East downloads the nordic's toolchaing manager for linux automatically (I had to replace the file with the correspoding mac os build from nordics' repo and use OS system settings to allow it to run), see path in the screenshot below:
![image](https://github.com/IRNAS/irnas-east-software/assets/27289158/c29bf074-cd97-40dd-a8ce-b1a28c95fffe)

East fails to install codechecker with the errow in the screenshot below:
![image](https://github.com/IRNAS/irnas-east-software/assets/27289158/2c202e61-278d-4f3b-8c78-38fe245ccead)

Also the help messages need to be updated:
- message to install the toolchain for the project needs to be changed from `east update toolchain` to `east install toolchain`

**Comment by MarkoSagadin** [comment]
This was resolved in e25e4846d6a813af568023a649e10a6aabc48217
